# -*- coding: utf-8 -*-
"""fx_risk_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOvXNvGsdNtfdNf7vqQ6_VRBmVDD7oA5
"""

"""
Ajoute :
1) VaR Historique roulante + ES (Expected Shortfall) roulante
2) Backtesting de VaR (comptage des breaches)
3) Risk controller :
   - Circuit breakers (perte journalière)
   - Deleveraging par drawdown (paliers d'exposition)
   - Stress de corrélation (retours, pas prix)
4) Turnover + coûts (si weights.csv fourni)
5) Stress tests simples (historique worst-days + shocks)

"""

from __future__ import annotations

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

CONFIG = {
    # Fenêtres roulantes
    "var_window": 252,          # VaR/ES sur 1 an glissant
    "corr_window": 63,          # corrélation sur 3 mois glissants

    # Niveau VaR/ES
    "alpha": 0.95,              # VaR 95%

    # Seuil stress corrélation (moyenne abs corr off-diagonal)
    "corr_abs_mean_threshold": 0.35,

    # Circuit breakers sur rendement quotidien (en simple return)
    # IMPORTANT: on convertira log-return -> simple-return avant d'appliquer ces seuils
    "daily_loss_cut": -0.02,    # -2% => couper exposition à 50%
    "daily_loss_flat": -0.04,   # -4% => exposition 0% (flat)

    # Deleveraging par drawdown (drawdown en % depuis le pic)
    # Liste de paliers : (drawdown_threshold, exposure_multiplier)
    "dd_exposure_tiers": [
        (0.00, 1.00),   # DD < 0%   -> 100%
        (0.05, 0.80),   # DD >= 5%  -> 80%
        (0.10, 0.60),   # DD >= 10% -> 60%
        (0.15, 0.40),   # DD >= 15% -> 40%
        (0.20, 0.00),   # DD >= 20% -> STOP
    ],

    # Coûts (très simple) : coût = turnover * bps
    # turnover = sum(|w_t - w_{t-1}|)/2
    "cost_bps_per_turnover": 2.0,  # 2 bps par 100% de turnover

    # Stress tests
    "stress_n_worst_days": 20,      # prend les 20 pires jours historiques
    "shock_sigma_levels": [2, 3],   # choc -2σ et -3σ

    # Fichiers
    "returns_path": "fx_returns.csv",
    "weights_path": "weights.csv",  # optionnel
    "out_dir": "risk_outputs",
}

def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def load_returns(path: str) -> pd.DataFrame:
    """
    Charge fx_returns.csv au format de votre projet :
    - sep=";"
    - decimal=","
    - index_col=0 = Date
    - valeurs = log returns

    On nettoie :
    - drop colonnes trop vides
    - drop lignes complètement vides
    """
    df = pd.read_csv(path, sep=";", decimal=",", index_col=0, parse_dates=True).sort_index()
    df = df.dropna(axis=1, thresh=200)
    df = df.dropna(how="all")
    return df


def load_weights(path: str, columns: list[str], index: pd.DatetimeIndex) -> pd.DataFrame | None:
    """
    Charge weights.csv si présent.
    Exigences :
    - mêmes colonnes que returns (ou sous-ensemble)
    - mêmes dates (ou dates moins fréquentes -> forward-fill)

    Si absent -> None.
    """
    if not os.path.exists(path):
        return None

    w = pd.read_csv(path, sep=";", decimal=",", index_col=0, parse_dates=True).sort_index()

    # aligne colonnes / dates
    w = w.reindex(columns=columns)
    w = w.reindex(index=index).ffill()

    # remplace NaN par 0 (poids absent)
    w = w.fillna(0.0)

    # renormalise pour que sum(w)=1 chaque jour (si somme=0 -> tout 0)
    s = w.sum(axis=1).replace(0.0, np.nan)
    w = w.div(s, axis=0).fillna(0.0)

    return w


def make_equal_weights(columns: list[str], index: pd.DatetimeIndex) -> pd.DataFrame:
    """Poids égal-pondérés (fallback)"""
    n = len(columns)
    return pd.DataFrame(1.0 / n, index=index, columns=columns)


def log_to_simple(r_log: pd.Series) -> pd.Series:
    """Convertit log-return -> simple return : exp(r)-1"""
    return np.exp(r_log) - 1.0



# 1) VAR HISTORIQUE + ES (ROULANTS)

def rolling_hist_var_es(r: pd.Series, window: int, alpha: float) -> pd.DataFrame:
    """
    Calcule VaR historique et ES (Expected Shortfall) sur fenêtre roulante.

    Convention :
    - VaR et ES sont des nombres POSITIFS représentant une perte.
    - VaR = -quantile(r, 1-alpha)
    - ES  = -moyenne(r | r <= quantile)

    r = série de rendements (ici log-returns ou simple returns, mais rester cohérent)
    """
    out = pd.DataFrame(index=r.index, columns=["VaR_hist", "ES_hist"], dtype=float)

    vals = r.values
    for i in range(len(r)):
        if i + 1 < window:
            continue

        w = vals[i + 1 - window : i + 1]
        w = w[~np.isnan(w)]
        if len(w) < max(30, window // 3):
            continue

        q = np.quantile(w, 1.0 - alpha)   # quantile de la queue gauche
        var = -q                          # perte positive
        tail = w[w <= q]
        es = -tail.mean() if len(tail) > 0 else np.nan

        out.iloc[i, 0] = var
        out.iloc[i, 1] = es

    return out


# 2) BACKTESTING VAR (BREACHES)

def var_breaches(r: pd.Series, var_series: pd.Series) -> pd.Series:
    """
    Un breach VaR se produit si :
      r < -VaR
    car VaR est une perte positive.

    Retourne une série 1/0 (NaN si VaR indisponible).
    """
    breach = (r < -var_series).astype(float)
    breach[var_series.isna()] = np.nan
    breach.name = "VaR_breach"
    return breach


def summarize_breaches(breach: pd.Series, alpha: float) -> dict:
    """Résumé du backtest VaR (taux observé vs attendu)"""
    b = breach.dropna()
    if len(b) == 0:
        return {
            "n_obs": 0,
            "n_breaches": 0,
            "breach_rate": np.nan,
            "expected_rate": 1.0 - alpha,
        }

    n = len(b)
    nb = int(b.sum())
    return {
        "n_obs": int(n),
        "n_breaches": nb,
        "breach_rate": float(nb / n),
        "expected_rate": float(1.0 - alpha),
    }


# 3) DRAWDOWN + RISK CONTROLLER

def equity_from_log_returns(r_log: pd.Series) -> pd.Series:
    """Equity curve base 1 à partir de log returns"""
    return np.exp(r_log.cumsum())


def drawdown_from_equity(equity: pd.Series) -> pd.Series:
    """Drawdown (négatif ou 0)"""
    peak = equity.cummax()
    return (equity - peak) / peak


def exposure_from_drawdown(dd_mag: float, tiers: list[tuple[float, float]]) -> float:
    """
    dd_mag = drawdown en valeur positive (ex: 0.12 pour -12%)
    tiers: liste (seuil_dd, expo)

    On prend le dernier palier dont seuil <= dd_mag.
    """
    expo = tiers[0][1]
    for thr, m in tiers:
        if dd_mag >= thr:
            expo = m
    return float(expo)


def build_risk_controller(
    port_log_returns_net: pd.Series,
    tiers: list[tuple[float, float]],
    daily_cut: float,
    daily_flat: float,
) -> pd.DataFrame:
    """
    Construit une "gouvernance" de risque qui sort un multiplicateur d'exposition quotidien.

    - Deleveraging par drawdown (expo_dd)
    - Circuit breaker par perte journalière (expo_cb)
    - expo_final = min(expo_dd, expo_cb)

    IMPORTANT : on applique les seuils daily_cut/daily_flat en SIMPLE RETURNS.
    """
    equity = equity_from_log_returns(port_log_returns_net)
    dd = drawdown_from_equity(equity)              # négatif
    dd_mag = (-dd).clip(lower=0.0)                 # positif

    expo_dd = dd_mag.apply(lambda x: exposure_from_drawdown(float(x), tiers))
    expo_dd.name = "exposure_dd"

    # circuit breaker basé sur simple returns
    simple_r = log_to_simple(port_log_returns_net)
    expo_cb = pd.Series(1.0, index=simple_r.index, name="exposure_cb")
    expo_cb[simple_r <= daily_flat] = 0.0
    expo_cb[(simple_r <= daily_cut) & (simple_r > daily_flat)] = 0.5

    expo_final = pd.Series(
        np.minimum(expo_dd.values, expo_cb.values),
        index=simple_r.index,
        name="exposure_final",
    )

    return pd.DataFrame(
        {
            "equity": equity,
            "drawdown": dd,
            "drawdown_mag": dd_mag,
            "exposure_dd": expo_dd,
            "exposure_cb": expo_cb,
            "exposure_final": expo_final,
        }
    )



# 4) CORRELATION STRESS (SUR RETURNS)

def avg_abs_offdiag_corr(df: pd.DataFrame) -> float:
    """
    Moyenne des corrélations absolues hors diagonale.
    """
    corr = df.corr()
    if corr.shape[0] < 2:
        return np.nan
    m = corr.values
    n = m.shape[0]
    mask = ~np.eye(n, dtype=bool)
    return float(np.nanmean(np.abs(m[mask])))


def rolling_corr_stress(
    returns_df: pd.DataFrame, window: int, threshold: float
) -> pd.DataFrame:
    """
    Calcule :
    - corr_abs_mean (moyenne abs corr off-diagonal)
    - corr_stress_flag = 1 si > threshold
    """
    out = pd.DataFrame(index=returns_df.index, columns=["corr_abs_mean", "corr_stress_flag"], dtype=float)

    for i in range(len(returns_df)):
        if i + 1 < window:
            continue

        w = returns_df.iloc[i + 1 - window : i + 1]

        # garde uniquement colonnes suffisamment présentes
        w = w.dropna(axis=1, thresh=window // 2)

        # impose dates communes dans la fenêtre
        w = w.dropna(how="any")

        if w.shape[0] < max(30, window // 3) or w.shape[1] < 2:
            continue

        c = avg_abs_offdiag_corr(w)
        out.iloc[i, 0] = c
        out.iloc[i, 1] = 1.0 if (not np.isnan(c) and c > threshold) else 0.0

    return out



# 5) TURNOVER + COUTS

def turnover(weights_df: pd.DataFrame) -> pd.Series:
    """
    Turnover journalier standard :
      turnover_t = sum(|w_t - w_{t-1}|) / 2

    /2 permet d'interpréter comme "fraction de portefeuille tradée".
    """
    t = weights_df.diff().abs().sum(axis=1) / 2.0
    t.name = "turnover"
    return t


def apply_costs(
    port_log_returns_gross: pd.Series,
    turnover_series: pd.Series,
    cost_bps_per_turnover: float,
) -> pd.DataFrame:
    """
    Modèle ultra-simple :
    coût_t = turnover_t * (bps / 10000)
    r_net = r_gross - coût_t

    Retourne :
    - cost
    - port_log_returns_net
    """
    cost = turnover_series * (cost_bps_per_turnover / 10000.0)
    cost.name = "cost"
    r_net = (port_log_returns_gross - cost.fillna(0.0)).rename("port_log_returns_net")
    return pd.concat([cost, r_net], axis=1)



# 6) PORTEFEUILLE : RETURNS A PARTIR DE POIDS

def portfolio_log_returns(returns_df: pd.DataFrame, weights_df: pd.DataFrame) -> pd.Series:
    """
    Rendement log du portefeuille : somme(w * r) (approximation cohérente pour log returns)
    """
    aligned_r = returns_df.reindex(index=weights_df.index, columns=weights_df.columns)
    pr = (aligned_r * weights_df).sum(axis=1)
    pr.name = "port_log_returns_gross"
    return pr


# 7) STRESS TESTS (SIMPLES)

def stress_tests(
    port_simple_returns: pd.Series,
    n_worst: int,
    shock_sigmas: list[int],
) -> pd.DataFrame:
    """
    Stress tests très simples :
    A) "Worst days" : moyenne des n pires jours
    B) Chocs paramétriques : -k * sigma (sur simple returns)

    Retourne un tableau de pertes (positives).
    """
    r = port_simple_returns.dropna()
    if len(r) < 30:
        return pd.DataFrame({"stress_loss": [np.nan]}, index=["insufficient_data"])

    # A) worst days
    worst = r.nsmallest(min(n_worst, len(r)))
    worst_mean = -worst.mean()  # perte positive

    # B) shocks
    sigma = r.std()
    shocks = {f"shock_-{k}sigma": float(k * sigma) for k in shock_sigmas}

    rows = {
        "worst_days_mean_loss": float(worst_mean),
        **shocks,
    }
    return pd.DataFrame.from_dict(rows, orient="index", columns=["stress_loss"])




# REPORTING + PLOTS

def save_plots(out_dir: str, daily: pd.DataFrame) -> None:
    ensure_dir(out_dir)

    # Equity
    fig = plt.figure(figsize=(12, 5))
    plt.plot(daily.index, daily["equity"])
    plt.title("Equity curve (base 1)")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "equity.png"), dpi=150)
    plt.close(fig)

    # Drawdown
    fig = plt.figure(figsize=(12, 4))
    plt.plot(daily.index, daily["drawdown"])
    plt.title("Drawdown")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "drawdown.png"), dpi=150)
    plt.close(fig)

    # Rolling VaR/ES
    fig = plt.figure(figsize=(12, 4))
    plt.plot(daily.index, daily["VaR_hist"], label="VaR hist (+loss)")
    plt.plot(daily.index, daily["ES_hist"], label="ES hist (+loss)")
    plt.title("Rolling VaR / ES (historique)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "var_es.png"), dpi=150)
    plt.close(fig)

    # Breaches
    fig = plt.figure(figsize=(12, 3))
    b = daily["VaR_breach"].fillna(0.0)
    plt.plot(daily.index, b)
    plt.ylim(-0.1, 1.1)
    plt.title("VaR breaches (1 = breach)")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "var_breaches.png"), dpi=150)
    plt.close(fig)

    # Exposure multipliers
    fig = plt.figure(figsize=(12, 4))
    plt.plot(daily.index, daily["exposure_final"], label="exposure_final")
    plt.plot(daily.index, daily["exposure_dd"], alpha=0.7, label="exposure_dd")
    plt.plot(daily.index, daily["exposure_cb"], alpha=0.7, label="exposure_cb")
    plt.ylim(-0.05, 1.05)
    plt.title("Risk controller (exposure multipliers)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "exposure.png"), dpi=150)
    plt.close(fig)

    # Corr stress
    fig = plt.figure(figsize=(12, 4))
    plt.plot(daily.index, daily["corr_abs_mean"], label="avg |corr|")
    plt.plot(daily.index, daily["corr_stress_flag"], label="stress flag (1=yes)")
    plt.title("Rolling correlation stress (returns)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "corr_stress.png"), dpi=150)
    plt.close(fig)

    # Turnover/costs si dispo
    if "turnover" in daily.columns:
        fig = plt.figure(figsize=(12, 3))
        plt.plot(daily.index, daily["turnover"])
        plt.title("Turnover")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, "turnover.png"), dpi=150)
        plt.close(fig)

    if "cost" in daily.columns:
        fig = plt.figure(figsize=(12, 3))
        plt.plot(daily.index, daily["cost"])
        plt.title("Estimated daily costs")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, "costs.png"), dpi=150)
        plt.close(fig)


# MAIN PIPELINE RISQUE

def main(cfg: dict) -> None:
    ensure_dir(cfg["out_dir"])

    # 1) Charge returns
    returns_df = load_returns(cfg["returns_path"])
    # Important pour portefeuille : dates communes (sinon pondération/risque compliqué)
    returns_df = returns_df.dropna()

    # 2) Charge weights (ou égal-pondéré)
    w = load_weights(cfg["weights_path"], columns=list(returns_df.columns), index=returns_df.index)
    if w is None:
        w = make_equal_weights(columns=list(returns_df.columns), index=returns_df.index)

    # 3) Rendements portefeuille BRUTS
    port_gross = portfolio_log_returns(returns_df, w)

    # 4) Turnover + coûts => rendements NETS
    to = turnover(w)
    costs_and_net = apply_costs(port_gross, to, cfg["cost_bps_per_turnover"])
    port_net = costs_and_net["port_log_returns_net"]

    # 5) VaR/ES roulants (sur NET, plus réaliste)
    var_es = rolling_hist_var_es(port_net, window=cfg["var_window"], alpha=cfg["alpha"])

    # 6) Breaches VaR (backtest)
    breaches = var_breaches(port_net, var_es["VaR_hist"])

    # 7) Risk controller (drawdown + circuit breakers)
    controller = build_risk_controller(
        port_log_returns_net=port_net,
        tiers=cfg["dd_exposure_tiers"],
        daily_cut=cfg["daily_loss_cut"],
        daily_flat=cfg["daily_loss_flat"],
    )

    # 8) Corr stress (sur returns par paires)
    corr_stress = rolling_corr_stress(
        returns_df,
        window=cfg["corr_window"],
        threshold=cfg["corr_abs_mean_threshold"],
    )

    # 9) Assemble rapport journalier
    daily = pd.concat(
        [
            port_gross,
            costs_and_net["port_log_returns_net"],
            costs_and_net["cost"],
            to,
            var_es,
            breaches,
            controller,
            corr_stress,
        ],
        axis=1,
    )

    daily_path = os.path.join(cfg["out_dir"], "risk_report_daily.csv")
    daily.to_csv(daily_path, sep=";", decimal=",")
    print(f"[OK] {daily_path}")

    # 10) Résumé (breaches + stress tests + stats simples)
    breach_summary = summarize_breaches(daily["VaR_breach"], cfg["alpha"])

    # stress tests sur rendements SIMPLE nets
    port_net_simple = log_to_simple(port_net)
    stress = stress_tests(
        port_simple_returns=port_net_simple,
        n_worst=cfg["stress_n_worst_days"],
        shock_sigmas=cfg["shock_sigma_levels"],
    )

    # stats additionnelles
    max_dd = float(daily["drawdown"].min()) if "drawdown" in daily else np.nan
    corr_avg = float(np.nanmean(daily["corr_abs_mean"].values))
    corr_stress_days = int(np.nansum(daily["corr_stress_flag"].values))
    exposure_avg = float(np.nanmean(daily["exposure_final"].values))
    stop_days = int(np.nansum((daily["exposure_final"] == 0.0).astype(float).values))
    cost_total = float(np.nansum(daily["cost"].values))
    turnover_avg = float(np.nanmean(daily["turnover"].values))

    summary_rows = {
        "max_drawdown (negative)": max_dd,
        "corr_abs_mean_avg": corr_avg,
        "corr_stress_days": corr_stress_days,
        "exposure_avg": exposure_avg,
        "stop_trading_days": stop_days,
        "cost_total": cost_total,
        "turnover_avg": turnover_avg,
        **{f"VaR_backtest_{k}": v for k, v in breach_summary.items()},
    }

    summary_df = pd.DataFrame.from_dict(summary_rows, orient="index", columns=["value"])
    summary_path = os.path.join(cfg["out_dir"], "risk_summary.csv")
    summary_df.to_csv(summary_path, sep=";", decimal=",")
    print(f"[OK] {summary_path}")

    # Ajoute stress tests au même dossier
    stress_path = os.path.join(cfg["out_dir"], "risk_stress_tests.csv")
    stress.to_csv(stress_path, sep=";", decimal=",")
    print(f"[OK] {stress_path}")

    # 11) Plots
    save_plots(cfg["out_dir"], daily)
    print(f"[OK] Plots sauvegardés dans {cfg['out_dir']}")

    # 12) Affichage console rapide
    print("\n=== SUMMARY (preview) ===")
    print(summary_df.round(6))
    print("\n=== STRESS TESTS (preview) ===")
    print(stress.round(6))


if __name__ == "__main__":
    main(CONFIG)